name: ldd
description: "Fluttercon 2024 - Cat-like Development: Flutter for Efficiency"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  confetti: ^0.7.0
  device_preview: ^1.2.0
  equatable: ^2.0.5
  expression_ui_example:
    path: packages/expression_ui_example
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_deck: ^0.15.0
  gskinner_example:
    path: packages/gskinner_example
  optimistic_todo_app:
    path: packages/optimistic_todo_app
  rive: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/rive/
